language: java

sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9
  # - oraclejdk10
  - openjdk8
  - openjdk9
  - openjdk10

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/